server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://121.36.29.213:3306/java_learn
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    username: root
  mail:
    # 配置 SMTP 服务器地址
    host: smtp.qq.com
    # 发送者邮箱
    username: 813728594@qq.com
    # 配置密码，注意不是真正的密码，而是刚刚申请到的授权码
    password: mjinnhcbfaclbdfh
    # 端口号465或587
    port: 587
    # 默认的邮件编码为UTF-8
    default-encoding: UTF-8
    # 配置SSL 加密工厂
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        #表示开启 DEBUG 模式，这样，邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true